#!/bin/bash

# プロパティ
WORK=/work
DATA=/data
INPUT=hgnc_complete_set.txt
OUTPUT=hgnc_complete_set.ttl
URL=ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/$INPUT
FORCE_CONVERT=0

# オプションの読み取り
while getopts f OPT
do
  case $OPT in
    f)  FORCE_CONVERT=1
        ;;
  esac
done
shift  $(($OPTIND - 1))

cd $WORK

# アーカイブファイルのダウンロード
now=`date "+%Y%m%d-%H%M%S"`
echo "Started wget at $now"

wget -N $URL 2> /wget.log
chmod -R 666 $INPUT

now=`date "+%Y%m%d-%H%M%S"`
echo "Finished wget baseline at $now"

cat /wget.log
num_of_newfiles=`egrep " saved \[+[0-9]+\]" /wget.log | grep -v "'.listing' saved" | wc -l`

# アーカイブファイルに更新が無く、fオプションが指定されていない場合はコンバートを実行しない
if [ $num_of_newfiles -eq 0 ] && [ $FORCE_CONVERT -eq 0 ]; then
  echo
  echo "No RDF files were generated because no new files were found at the download site."
  exit 0
fi

# コンバートの実行
now=`date "+%Y%m%d-%H%M%S"`
echo "Started convert at $now"

ruby /hgnc/hgnc2ttl.rb ./$INPUT > /data/$OUTPUT

now=`date "+%Y%m%d-%H%M%S"`
echo "Finished convert at $now"

chmod -R 666 /data/$OUTPUT




